-- Thêm giao dịch
GO
ALTER PROC SP_THEM_GD_GOIRUT
	@SOTK NCHAR(9),
	@LOAIGD NCHAR(2),
	@SOTIEN MONEY,
	@MANV NCHAR(10)
AS
BEGIN
	IF @LOAIGD = 'RT' AND (SELECT SODU FROM TaiKhoan WHERE TaiKhoan.SOTK = @SOTK) < @SOTIEN
		RAISERROR('Số dư hiện tại không đủ để thực hiện rút tiền', 16, 1);
	ELSE
	BEGIN
		BEGIN TRAN
			INSERT INTO GD_GOIRUT(SOTK, LOAIGD, NGAYGD, SOTIEN, MANV)
			VALUES(@SOTK, @LOAIGD, GETDATE(), @SOTIEN, @MANV)
			IF @LOAIGD = 'GT'
				UPDATE TaiKhoan
				SET SODU = SODU + @SOTIEN
				WHERE SOTK = @SOTK
			ELSE
				UPDATE TaiKhoan
				SET SODU = SODU - @SOTIEN
				WHERE SOTK = @SOTK
		COMMIT TRAN
	END
END

-- Tìm họ tên khách hàng sở hữu số tài khoản
GO
ALTER PROCEDURE [dbo].[SP_TIM_KHACHHANG_SOTK] @SOTK NCHAR(9) AS
BEGIN
	IF NOT EXISTS (SELECT CMND FROM TaiKhoan WHERE SOTK = @SOTK)
		RAISERROR('Số tài khoản không tồn tại', 16, 1);
	ELSE
		IF EXISTS(SELECT TEN FROM KhachHang WHERE CMND = (SELECT CMND FROM TaiKhoan WHERE SOTK = @SOTK))
			SELECT HOTEN = HO + ' ' + TEN
			FROM KhachHang
			WHERE CMND = (SELECT CMND FROM TaiKhoan WHERE SOTK = @SOTK)
		ELSE
			SELECT HOTEN = HO + ' ' + TEN
			FROM LINK2.NGANHANG.DBO.KhachHang
			WHERE CMND = (SELECT CMND FROM TaiKhoan WHERE SOTK = @SOTK)
END

EXEC SP_TIM_KHACHHANG_SOTK 'TK001'

exec SP_THEM_GD_GOIRUT 'TK001', 'GT', 100000, 'ntt'
select IDENT_CURRENT('GD_GOIRUT') as id