USE [NGANHANG]
GO

/****** Object:  StoredProcedure [dbo].[SP_LIET_KE_TK_THEO_TG]    Script Date: 5/21/2022 10:06:53 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_LIET_KE_TK_THEO_TG] @CN NCHAR(10), @TUNGAY DATETIME, @DENNGAY DATETIME
AS
IF @CN = 'ALL'
	SELECT SOTK, CMND, SODU, MACN, NGAYMOTK FROM TaiKhoan WHERE NGAYMOTK >= @TUNGAY AND NGAYMOTK <= @DENNGAY
ELSE
	SELECT SOTK, CMND, SODU, MACN, NGAYMOTK FROM TaiKhoan WHERE MACN = @CN AND NGAYMOTK >= @TUNGAY AND NGAYMOTK <= @DENNGAY
GO


