USE [NGANHANG]
GO

/****** Object:  StoredProcedure [dbo].[SP_THEM_KHACHHANG]    Script Date: 5/21/2022 10:05:23 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_THEM_KHACHHANG]
	@CMND NCHAR(10), 
	@HO NVARCHAR(50), 
	@TEN NVARCHAR(10), 
	@DIACHI NVARCHAR(100),
	@PHAI NVARCHAR(3),
	@NGAYCAP DATE,
	@SODT NVARCHAR(15), 
	@MACN NCHAR(10)
AS
BEGIN
	IF EXISTS (SELECT CMND FROM KhachHang WHERE CMND = @CMND)
		RAISERROR(N'Khách hàng đã tồn tại ở chi nhánh hiện tại', 16, 1);
	ELSE IF EXISTS (SELECT CMND FROM LINK2.NGANHANG.DBO.KhachHang WHERE CMND = @CMND)
		RAISERROR(N'Khách hàng đã tồn tại ở chi nhánh khác', 16, 1);
	ELSE IF EXISTS(SELECT SODT FROM KhachHang WHERE SODT = @SODT)
		RAISERROR(N'Số điện thoại trùng', 16, 1);
	ELSE IF EXISTS(SELECT SODT FROM LINK2.NGANHANG.DBO.KhachHang WHERE SODT = @SODT)
		RAISERROR(N'Số điện thoại trùng', 16, 1);
	ELSE
		INSERT INTO KhachHang(CMND, HO, TEN, DIACHI, PHAI, NGAYCAP, SODT, MACN)
		VALUES(@CMND, @HO, @TEN, @DIACHI, @PHAI, @NGAYCAP, @SODT, @MACN)
END

GO

CREATE PROCEDURE [dbo].[SP_CAPNHAT_KHACHHANG] @CMND NCHAR(10), 
	@HO NVARCHAR(50), 
	@TEN NVARCHAR(10), 
	@DIACHI NVARCHAR(100),
	@PHAI NVARCHAR(3),
	@NGAYCAP DATE,
	@SODT NVARCHAR(15)
AS
BEGIN
	IF EXISTS(SELECT * FROM KhachHang WHERE SODT = @SODT)
		RAISERROR(N'Số điện thoại trùng', 16, 1);
	ELSE IF EXISTS(SELECT * FROM LINK2.NGANHANG.DBO.KhachHang WHERE SODT = @SODT)
		RAISERROR(N'Số điện thoại trùng', 16, 1);
	ELSE
	UPDATE KhachHang
	SET HO = @HO, TEN = @TEN, DIACHI = @DIACHI, PHAI = @PHAI, NGAYCAP = @NGAYCAP, SODT = @SODT
	WHERE CMND = @CMND
END
GO


CREATE PROC [dbo].[SP_XOA_KHACHHANG]
	@CMND NCHAR(10)
AS
BEGIN
	IF EXISTS (SELECT * FROM TaiKhoan WHERE CMND = @CMND)
		RAISERROR(N'Không thể xóa vì khách hàng đã có tài khoản', 16, 1);
	ELSE
		DELETE KhachHang
		WHERE CMND = @CMND;
END

GO
