GO
CREATE PROC [dbo].[SP_CHUYEN_TIEN]
	@SOTK_CHUYEN NCHAR(9),
	@SOTK_NHAN NCHAR(9),
	@SOTIEN MONEY,
	@MANV NCHAR(10)
AS
BEGIN
	SET XACT_ABORT ON
	BEGIN TRANSACTION

	BEGIN TRY
		UPDATE TaiKhoan 
		SET SODU = SODU+ @SOTIEN WHERE SOTK= @SOTK_NHAN

		UPDATE TAIKHOAN 
		SET SODU = SODU -  @SOTIEN WHERE SOTK= @SOTK_CHUYEN 

		INSERT INTO GD_CHUYENTIEN(SOTK_CHUYEN, NGAYGD, SOTIEN, SOTK_NHAN, MANV)
			VALUES(@SOTK_CHUYEN, GETDATE(), @SOTIEN, @SOTK_NHAN, @MANV)
 
		COMMIT
	END TRY

	BEGIN CATCH
		ROLLBACK
		RAISERROR(N'Chuyển tiền thất bại, số dư tài khoản chuyển không đủ', 16, 1)	
	END CATCH
END