GO
ALTER PROC SP_TIM_KHACHHANG @CMND NCHAR(10)
AS
BEGIN
	IF EXISTS (SELECT CMND FROM KhachHang WHERE CMND = @CMND)
		SELECT HO + ' ' + TEN AS N'Họ và tên' FROM KhachHang WHERE CMND = @CMND
	ELSE IF EXISTS (SELECT CMND FROM LINK2.NGANHANG.DBO.KhachHang WHERE CMND = @CMND)
		SELECT HO + ' ' + TEN AS N'Họ và tên' FROM LINK2.NGANHANG.DBO.KhachHang 
		WHERE CMND = @CMND
	ELSE
		RAISERROR(N'Khách hàng không tồn tại', 16, 1);
END

GO
ALTER PROC SP_THEM_TAIKHOAN
	@SOTK NCHAR(9),
	@CMND NCHAR(10),
	@SODU MONEY,
	@MACN NCHAR(10),
	@NGAYMOTK DATETIME
AS
BEGIN
	--IF EXISTS (SELECT SOTK FROM TaiKhoan WHERE SOTK = @SOTK)
	--	RAISERROR(N'Số tài khoản đã tồn tại', 16, 1);
	----THÊM TÀI KHOẢN TẠI CHI NHÁNH HIỆN TẠI
	--ELSE IF EXISTS (SELECT CMND FROM KhachHang WHERE CMND = @CMND)
	--	INSERT INTO TaiKhoan(SOTK, CMND, SODU, MACN, NGAYMOTK)
	--	VALUES(@SOTK, @CMND, @SODU, @MACN, @NGAYMOTK)
	--ELSE IF NOT EXISTS (SELECT CMND FROM LINK2.NGANHANG.DBO.KHACHHANG WHERE CMND = @CMND)
	--	RAISERROR(N'Khách hàng không tồn tại', 16, 1);
	--ELSE 
	--	INSERT INTO TaiKhoan(SOTK, CMND, SODU, MACN, NGAYMOTK)
	--	VALUES(@SOTK, @CMND, @SODU, @MACN, @NGAYMOTK)


	-- NEW
	IF EXISTS (SELECT SOTK FROM TaiKhoan WHERE SOTK = @SOTK)
		RAISERROR(N'Số tài khoản đã tồn tại', 16, 1);
	ELSE IF NOT EXISTS(SELECT CMND FROM KhachHang WHERE CMND = @CMND) AND NOT EXISTS(SELECT CMND FROM LINK2.NGANHANG.DBO.KHACHHANG WHERE CMND = @CMND)
		RAISERROR(N'Khách hàng không tồn tại', 16, 1);
	ELSE
		INSERT INTO TaiKhoan(SOTK, CMND, SODU, MACN, NGAYMOTK)
		VALUES(@SOTK, @CMND, @SODU, @MACN, @NGAYMOTK)
END

-- Xóa tài khoản -> Phục hồi sau khi mở tài khoản
GO
CREATE PROC SP_XOA_TAIKHOAN_GD @SOTK NCHAR(9) AS
BEGIN
	IF
	EXISTS (SELECT MAGD FROM GD_GOIRUT WHERE SOTK = @SOTK) OR
	EXISTS (SELECT MAGD FROM GD_CHUYENTIEN WHERE SOTK_CHUYEN = @SOTK OR SOTK_NHAN = @SOTK) OR
	EXISTS (SELECT MAGD FROM LINK1.NGANHANG.DBO.GD_GOIRUT WHERE SOTK = @SOTK) OR
	EXISTS (SELECT MAGD FROM LINK1.NGANHANG.DBO.GD_CHUYENTIEN WHERE SOTK_CHUYEN = @SOTK OR SOTK_NHAN = @SOTK)
		RAISERROR('Không thể xóa tài khoản này do đã có giao dịch được thực hiện', 16, 1);
	ELSE
		DELETE TaiKhoan
		WHERE SOTK = @SOTK
END

EXEC SP_XOA_TAIKHOAN_GD '111111111'